# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  install:
    aliases: [i]
    cmds:
      - uv pip install
      - npm install
  python:
    cmds:
      - uv run python ./run.py --root-dir ./src/lib/sixth-chamber/doc --output-dir ./src/lib/mawanet --whitelist ./src/lib/sixth-chamber/whitelist.json
  build:
    aliases: [b]
    cmds:
      - task: python
      - npm run build
  preview:
    aliases: [p]
    cmds:
      - npm run preview
  dev:
    aliases: [d]
    cmds:
      - task: python
      - npm run dev
