# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  install:
    aliases: [i]
    cmds:
      - uv venv  --python-preference only-managed --python 3.13 .venv
      - npm install
  python:
    cmds:
      - |
        uv run python ./mdx-worker.py \
        --root-dir ./src/lib/sixth-chamber/doc \
        --output-dir ./src/lib/mawanet \
        --whitelist ./src/lib/sixth-chamber/whitelist.json \
        --mtt
      - |
        uv run python ./mdx-worker.py \
        --root-dir ./src/lib/entries/sk/rebis-theory \
        --output-dir ./src/lib/entries/sk/mdx \
        --whitelist ./src/lib/entries/sk/whitelist.json \
  build:
    aliases: [b]
    cmds:
      - task: python
      - npm run build
  preview:
    aliases: [p]
    cmds:
      - npm run preview
  dev:
    aliases: [d]
    cmds:
      - task: python
      - npm run dev
